version: '3.8'
name: avatares

services:
  backend:
    image: pablokonig/avatares-backend:v0.0.1
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"

  frontend:
    image: pablokonig/avatares-frontend:v0.0.1
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    