apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatares-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avatares-backend
  template:
    metadata:
      labels:
        app: avatares-backend
    spec:
      containers:
      - name: avatares-backend
        image: pablokonig/backend:v0.0.1
        ports:
        - containerPort: 5000                                               # Puerto del backend
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "development"