apiVersion: v1
kind: Service
metadata:
  name: avatares-frontend-service
spec:
  selector:
    app: avatares-frontend
  type: LoadBalancer                                      # Expone el frontend públicamente
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173