name: CI/CD Pipeline DevOps                                     # Nombre del workflow

on:                                                             # Define cuándo se ejecuta el workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main                                                    # Se ejecutará en cada push a la rama "main"

jobs:                                                           # Define los trabajos a ejecutar en el workflow
  build:                                                        # Nombre del primer trabajo
    runs-on: ubuntu-latest                                      # Sistema operativo para ejecutar el trabajo

    steps:                                                      # Pasos a ejecutar dentro del trabajo
      - name: Clonar Repo                                       # Nombre del paso
        uses: actions/checkout@v4                               # Acción predefinida para clonar el repositorio
        
      - name: Print GITHUB_REF
        run: 
          echo "GITHUB_REF : $GITHUB_REF"
        
      - name: Definir version
        if: startsWith(github.ref, 'refs/tags/')                # Se Establece la variable desde el tag para versionar las imágenes de Docker Hub.
        run: |
          echo "v1.0.1" >> $GITHUB_ENV
          # echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV    

      - name: Login a Docker Hub                                # Inicia sesión en Docker Hub
        uses: docker/login-action@v1                            # Acción para autenticarse en Docker Hub
        with:                                                   # Parámetros para la acción
          username: ${{ secrets.DOCKER_HUB_USERNAME }}          # Usuario de Docker Hub (secreto)
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}          # Contraseña de Docker Hub (secreto)

      - name: Build and push imagen BackEnd                     # Construye y sube la imagen del backend
        uses: docker/build-push-action@v2                       # Acción para construir y subir imágenes Docker
        with:
          context: ./Backend                                    # Directorio con el Dockerfile del backend
          push: true                                            # Habilita la subida a Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/avatares-backend:${{ env.VERSION }}  # Nombre de la imagen en Docker Hub

      - name: Build and push frontend image                     # Construye y sube la imagen del frontend
        uses: docker/build-push-action@v2                       # Acción para construir y subir imágenes Docker
        with:
          context: ./Frontend                                   # Directorio con el Dockerfile del frontend
          push: true                                            # Habilita la subida a Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/avatares-frontend:${{ env.VERSION }}   # Nombre de la imagen en Docker Hub
